### PR TITLE
fixed #20

### LINKED ISSUE #20: Specs pass on crystal 0.10.0 but fails on travis ci.
When running specs on crystal versions `0.10.0` everything works fine,  but on `0.10.1` (which is the latest build, hence travis runs that build) it fails giving following error :

```
Error in ./libs/spec2/reporter.cr:8: abstract `def Spec2::Reporter#example_failed(example)` must be implemented by Spec2::Reporters::Default

    abstract def example_failed(example)

                 ^~~~~~~~~~~~~~
```

I think this is due to the fact that latest crystal checks that abstract methods are implemented or not.
Here's the failing build on [travis](https://travis-ci.org/vjdhama/ambience/builds/101280604).

### PR DESCRIPTION
**Pull request by vjdhama**
This fixes the issue #20 .

### CODE REVIEW

**Comment by waterlink** [comment]
@vjdhama Thanks! LGTM

**Comment by vjdhama** [comment]
Thanks @waterlink. I can't use the merged changes since there's no new release for shards to pull from. Could you possibly release a new version?

**Comment by waterlink** [comment]
@vjdhama I will do that.

On the side note, you actually can:

``` yaml
dependencies:
  spec2:
    github: waterlink/spec2.cr
    branch: master
```

This will use latest code from `master` branch after running `shards update`.

**Comment by waterlink** [comment]
@vjdhama Done

**Comment by vjdhama** [comment]
@waterlink Thanks again. Didn't know you could pass branch in there.

**Pull request merged**
