### PR TITLE
Add described_class feature

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
It looks like the build is failing because it could not install Crystal. :(

**Comment by waterlink** [comment]
This will be fixed soon here: https://github.com/travis-ci/travis-build/pull/764

I will check it manually and merge if everything is OK.

Thank you! :+1:

**Comment by waterlink** [comment]
I have released `0.9.0` with this feature in.

**Comment by mauricioabreu** [comment]
Thank you for helping me! :+1:

**Pull request merged**
